module.exports = {
  array: require("./array"),
  exactNumber: require("./exactNumber"),
  exactString: require("./exactString"),
  func: require("./func"),
  instanceOf: require("./instanceOf"),
  intersection: require("./intersection"),
  map: require("./map"),
  maybe: require("./maybe"),
  object: require("./object"),
  objectMap: require("./objectMap"),
  set: require("./set"),
  shape: require("./shape"),
  symbolFor: require("./symbolFor"),
  tuple: require("./tuple"),
  union: require("./union"),
};
